import { MigrationInterface, QueryRunner } from "typeorm";

export class PublicAndFileImagesTablesAndUpdates1666907020374 implements MigrationInterface {
    name = 'PublicAndFileImagesTablesAndUpdates1666907020374'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`starship_pilots_person\` DROP FOREIGN KEY \`FK_c288e78f5f06c73e7f7dc0d0987\``);
        await queryRunner.query(`ALTER TABLE \`vehicle_pilots_person\` DROP FOREIGN KEY \`FK_c73dfb1a6855a3090a53f1775db\``);
        await queryRunner.query(`ALTER TABLE \`person_species_species\` DROP FOREIGN KEY \`FK_57bacd286664d61d21d5bd226db\``);
        await queryRunner.query(`ALTER TABLE \`film_characters_person\` DROP FOREIGN KEY \`FK_ac77e50e8297245fc2dec2208c5\``);
        await queryRunner.query(`ALTER TABLE \`film_planets_planet\` DROP FOREIGN KEY \`FK_ab8496e34e9348472fa6297afad\``);
        await queryRunner.query(`ALTER TABLE \`film_starships_starship\` DROP FOREIGN KEY \`FK_31c21f4a2e9b82e67edb2c0fce2\``);
        await queryRunner.query(`ALTER TABLE \`film_vehicles_vehicle\` DROP FOREIGN KEY \`FK_06a000ce716c9d51c5aab52d924\``);
        await queryRunner.query(`ALTER TABLE \`film_species_species\` DROP FOREIGN KEY \`FK_f24ab6fc37cb0682cc6e9ecbea6\``);
        await queryRunner.query(`CREATE TABLE \`file_image\` (\`id\` int NOT NULL AUTO_INCREMENT, \`file_name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`public_image\` (\`id\` int NOT NULL AUTO_INCREMENT, \`url\` varchar(255) NOT NULL, \`key\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`species_public_images_public_image\` (\`species_id\` int NOT NULL, \`public_image_id\` int NOT NULL, INDEX \`IDX_d99989c589c00013b81c3a3b3b\` (\`species_id\`), INDEX \`IDX_8542c2cb80cd87ed017de247b4\` (\`public_image_id\`), PRIMARY KEY (\`species_id\`, \`public_image_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`species_file_images_file_image\` (\`species_id\` int NOT NULL, \`file_image_id\` int NOT NULL, INDEX \`IDX_a28aa9ef8ff2322342334e91f7\` (\`species_id\`), INDEX \`IDX_b5e76ce0c5ce1249d7fe8857f0\` (\`file_image_id\`), PRIMARY KEY (\`species_id\`, \`file_image_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`planet_public_images_public_image\` (\`planet_id\` int NOT NULL, \`public_image_id\` int NOT NULL, INDEX \`IDX_5e3ba9988de63b7c2428979f06\` (\`planet_id\`), INDEX \`IDX_02c5bb34fb700872404edb40a6\` (\`public_image_id\`), PRIMARY KEY (\`planet_id\`, \`public_image_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`planet_file_images_file_image\` (\`planet_id\` int NOT NULL, \`file_image_id\` int NOT NULL, INDEX \`IDX_4def93684640f79d8b410292d0\` (\`planet_id\`), INDEX \`IDX_c3333884b9d04c6c185f8695e3\` (\`file_image_id\`), PRIMARY KEY (\`planet_id\`, \`file_image_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`starship_public_images_public_image\` (\`starship_id\` int NOT NULL, \`public_image_id\` int NOT NULL, INDEX \`IDX_16dde91fda64eeb31e5baa1b65\` (\`starship_id\`), INDEX \`IDX_9f5a82d306b4d5ccded99965a7\` (\`public_image_id\`), PRIMARY KEY (\`starship_id\`, \`public_image_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`starship_file_images_file_image\` (\`starship_id\` int NOT NULL, \`file_image_id\` int NOT NULL, INDEX \`IDX_70c9f6c4cbf97078fec8a3c3f4\` (\`starship_id\`), INDEX \`IDX_1f9ba49219eba1e6bff2a6d0c8\` (\`file_image_id\`), PRIMARY KEY (\`starship_id\`, \`file_image_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vehicle_public_images_public_image\` (\`vehicle_id\` int NOT NULL, \`public_image_id\` int NOT NULL, INDEX \`IDX_4cf8fe8129ab729e46f3b656ca\` (\`vehicle_id\`), INDEX \`IDX_e7ac12dd5b1b78be3b73e36a27\` (\`public_image_id\`), PRIMARY KEY (\`vehicle_id\`, \`public_image_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vehicle_file_images_file_image\` (\`vehicle_id\` int NOT NULL, \`file_image_id\` int NOT NULL, INDEX \`IDX_2bcc119990ead7945ef8d0451c\` (\`vehicle_id\`), INDEX \`IDX_c0467899515f18bb82e5053e7a\` (\`file_image_id\`), PRIMARY KEY (\`vehicle_id\`, \`file_image_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`person_public_images_public_image\` (\`person_id\` int NOT NULL, \`public_image_id\` int NOT NULL, INDEX \`IDX_e6219cda4da6e388190be2389d\` (\`person_id\`), INDEX \`IDX_18da4152da165885e90279fca2\` (\`public_image_id\`), PRIMARY KEY (\`person_id\`, \`public_image_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`person_file_images_file_image\` (\`person_id\` int NOT NULL, \`file_image_id\` int NOT NULL, INDEX \`IDX_2c3ae1c800f91b77685ab2beda\` (\`person_id\`), INDEX \`IDX_2f57c18a8452577561758c646d\` (\`file_image_id\`), PRIMARY KEY (\`person_id\`, \`file_image_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`film_public_images_public_image\` (\`film_id\` int NOT NULL, \`public_image_id\` int NOT NULL, INDEX \`IDX_9aaf17ea2ecaf60637e871c14e\` (\`film_id\`), INDEX \`IDX_b2b751a688065c8c8a1add7de2\` (\`public_image_id\`), PRIMARY KEY (\`film_id\`, \`public_image_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`film_file_images_file_image\` (\`film_id\` int NOT NULL, \`file_image_id\` int NOT NULL, INDEX \`IDX_2b92c5667c380b56597819981e\` (\`film_id\`), INDEX \`IDX_ad877fc7ae8d3269c736ec6c2e\` (\`file_image_id\`), PRIMARY KEY (\`film_id\`, \`file_image_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`planet\` ADD \`diameter\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`species\` DROP FOREIGN KEY \`FK_f7e93a1974cc86fd87ce6777319\``);
        await queryRunner.query(`ALTER TABLE \`species\` CHANGE \`homeworld_id\` \`homeworld_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`person\` DROP FOREIGN KEY \`FK_e9797533c90a8211d39784488f3\``);
        await queryRunner.query(`ALTER TABLE \`person\` CHANGE \`homeworld_id\` \`homeworld_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`species\` ADD CONSTRAINT \`FK_f7e93a1974cc86fd87ce6777319\` FOREIGN KEY (\`homeworld_id\`) REFERENCES \`planet\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`person\` ADD CONSTRAINT \`FK_e9797533c90a8211d39784488f3\` FOREIGN KEY (\`homeworld_id\`) REFERENCES \`planet\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`species_public_images_public_image\` ADD CONSTRAINT \`FK_d99989c589c00013b81c3a3b3b0\` FOREIGN KEY (\`species_id\`) REFERENCES \`species\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`species_public_images_public_image\` ADD CONSTRAINT \`FK_8542c2cb80cd87ed017de247b4e\` FOREIGN KEY (\`public_image_id\`) REFERENCES \`public_image\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`species_file_images_file_image\` ADD CONSTRAINT \`FK_a28aa9ef8ff2322342334e91f7e\` FOREIGN KEY (\`species_id\`) REFERENCES \`species\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`species_file_images_file_image\` ADD CONSTRAINT \`FK_b5e76ce0c5ce1249d7fe8857f0e\` FOREIGN KEY (\`file_image_id\`) REFERENCES \`file_image\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`planet_public_images_public_image\` ADD CONSTRAINT \`FK_5e3ba9988de63b7c2428979f066\` FOREIGN KEY (\`planet_id\`) REFERENCES \`planet\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`planet_public_images_public_image\` ADD CONSTRAINT \`FK_02c5bb34fb700872404edb40a6f\` FOREIGN KEY (\`public_image_id\`) REFERENCES \`public_image\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`planet_file_images_file_image\` ADD CONSTRAINT \`FK_4def93684640f79d8b410292d08\` FOREIGN KEY (\`planet_id\`) REFERENCES \`planet\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`planet_file_images_file_image\` ADD CONSTRAINT \`FK_c3333884b9d04c6c185f8695e37\` FOREIGN KEY (\`file_image_id\`) REFERENCES \`file_image\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`starship_pilots_person\` ADD CONSTRAINT \`FK_c288e78f5f06c73e7f7dc0d0987\` FOREIGN KEY (\`pilot_id\`) REFERENCES \`person\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`starship_public_images_public_image\` ADD CONSTRAINT \`FK_16dde91fda64eeb31e5baa1b651\` FOREIGN KEY (\`starship_id\`) REFERENCES \`starship\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`starship_public_images_public_image\` ADD CONSTRAINT \`FK_9f5a82d306b4d5ccded99965a7c\` FOREIGN KEY (\`public_image_id\`) REFERENCES \`public_image\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`starship_file_images_file_image\` ADD CONSTRAINT \`FK_70c9f6c4cbf97078fec8a3c3f4c\` FOREIGN KEY (\`starship_id\`) REFERENCES \`starship\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`starship_file_images_file_image\` ADD CONSTRAINT \`FK_1f9ba49219eba1e6bff2a6d0c8b\` FOREIGN KEY (\`file_image_id\`) REFERENCES \`file_image\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`vehicle_pilots_person\` ADD CONSTRAINT \`FK_c73dfb1a6855a3090a53f1775db\` FOREIGN KEY (\`pilot_id\`) REFERENCES \`person\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vehicle_public_images_public_image\` ADD CONSTRAINT \`FK_4cf8fe8129ab729e46f3b656ca2\` FOREIGN KEY (\`vehicle_id\`) REFERENCES \`vehicle\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`vehicle_public_images_public_image\` ADD CONSTRAINT \`FK_e7ac12dd5b1b78be3b73e36a273\` FOREIGN KEY (\`public_image_id\`) REFERENCES \`public_image\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`vehicle_file_images_file_image\` ADD CONSTRAINT \`FK_2bcc119990ead7945ef8d0451cf\` FOREIGN KEY (\`vehicle_id\`) REFERENCES \`vehicle\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`vehicle_file_images_file_image\` ADD CONSTRAINT \`FK_c0467899515f18bb82e5053e7a9\` FOREIGN KEY (\`file_image_id\`) REFERENCES \`file_image\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`person_species_species\` ADD CONSTRAINT \`FK_57bacd286664d61d21d5bd226db\` FOREIGN KEY (\`species_id\`) REFERENCES \`species\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`person_public_images_public_image\` ADD CONSTRAINT \`FK_e6219cda4da6e388190be2389d5\` FOREIGN KEY (\`person_id\`) REFERENCES \`person\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`person_public_images_public_image\` ADD CONSTRAINT \`FK_18da4152da165885e90279fca22\` FOREIGN KEY (\`public_image_id\`) REFERENCES \`public_image\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`person_file_images_file_image\` ADD CONSTRAINT \`FK_2c3ae1c800f91b77685ab2bedae\` FOREIGN KEY (\`person_id\`) REFERENCES \`person\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`person_file_images_file_image\` ADD CONSTRAINT \`FK_2f57c18a8452577561758c646d2\` FOREIGN KEY (\`file_image_id\`) REFERENCES \`file_image\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`film_characters_person\` ADD CONSTRAINT \`FK_ac77e50e8297245fc2dec2208c5\` FOREIGN KEY (\`character_id\`) REFERENCES \`person\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`film_planets_planet\` ADD CONSTRAINT \`FK_ab8496e34e9348472fa6297afad\` FOREIGN KEY (\`planet_id\`) REFERENCES \`planet\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`film_starships_starship\` ADD CONSTRAINT \`FK_31c21f4a2e9b82e67edb2c0fce2\` FOREIGN KEY (\`starship_id\`) REFERENCES \`starship\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`film_vehicles_vehicle\` ADD CONSTRAINT \`FK_06a000ce716c9d51c5aab52d924\` FOREIGN KEY (\`vehicle_id\`) REFERENCES \`vehicle\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`film_species_species\` ADD CONSTRAINT \`FK_f24ab6fc37cb0682cc6e9ecbea6\` FOREIGN KEY (\`species_id\`) REFERENCES \`species\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`film_public_images_public_image\` ADD CONSTRAINT \`FK_9aaf17ea2ecaf60637e871c14ea\` FOREIGN KEY (\`film_id\`) REFERENCES \`film\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`film_public_images_public_image\` ADD CONSTRAINT \`FK_b2b751a688065c8c8a1add7de27\` FOREIGN KEY (\`public_image_id\`) REFERENCES \`public_image\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`film_file_images_file_image\` ADD CONSTRAINT \`FK_2b92c5667c380b56597819981ec\` FOREIGN KEY (\`film_id\`) REFERENCES \`film\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`film_file_images_file_image\` ADD CONSTRAINT \`FK_ad877fc7ae8d3269c736ec6c2e7\` FOREIGN KEY (\`file_image_id\`) REFERENCES \`file_image\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`film_file_images_file_image\` DROP FOREIGN KEY \`FK_ad877fc7ae8d3269c736ec6c2e7\``);
        await queryRunner.query(`ALTER TABLE \`film_file_images_file_image\` DROP FOREIGN KEY \`FK_2b92c5667c380b56597819981ec\``);
        await queryRunner.query(`ALTER TABLE \`film_public_images_public_image\` DROP FOREIGN KEY \`FK_b2b751a688065c8c8a1add7de27\``);
        await queryRunner.query(`ALTER TABLE \`film_public_images_public_image\` DROP FOREIGN KEY \`FK_9aaf17ea2ecaf60637e871c14ea\``);
        await queryRunner.query(`ALTER TABLE \`film_species_species\` DROP FOREIGN KEY \`FK_f24ab6fc37cb0682cc6e9ecbea6\``);
        await queryRunner.query(`ALTER TABLE \`film_vehicles_vehicle\` DROP FOREIGN KEY \`FK_06a000ce716c9d51c5aab52d924\``);
        await queryRunner.query(`ALTER TABLE \`film_starships_starship\` DROP FOREIGN KEY \`FK_31c21f4a2e9b82e67edb2c0fce2\``);
        await queryRunner.query(`ALTER TABLE \`film_planets_planet\` DROP FOREIGN KEY \`FK_ab8496e34e9348472fa6297afad\``);
        await queryRunner.query(`ALTER TABLE \`film_characters_person\` DROP FOREIGN KEY \`FK_ac77e50e8297245fc2dec2208c5\``);
        await queryRunner.query(`ALTER TABLE \`person_file_images_file_image\` DROP FOREIGN KEY \`FK_2f57c18a8452577561758c646d2\``);
        await queryRunner.query(`ALTER TABLE \`person_file_images_file_image\` DROP FOREIGN KEY \`FK_2c3ae1c800f91b77685ab2bedae\``);
        await queryRunner.query(`ALTER TABLE \`person_public_images_public_image\` DROP FOREIGN KEY \`FK_18da4152da165885e90279fca22\``);
        await queryRunner.query(`ALTER TABLE \`person_public_images_public_image\` DROP FOREIGN KEY \`FK_e6219cda4da6e388190be2389d5\``);
        await queryRunner.query(`ALTER TABLE \`person_species_species\` DROP FOREIGN KEY \`FK_57bacd286664d61d21d5bd226db\``);
        await queryRunner.query(`ALTER TABLE \`vehicle_file_images_file_image\` DROP FOREIGN KEY \`FK_c0467899515f18bb82e5053e7a9\``);
        await queryRunner.query(`ALTER TABLE \`vehicle_file_images_file_image\` DROP FOREIGN KEY \`FK_2bcc119990ead7945ef8d0451cf\``);
        await queryRunner.query(`ALTER TABLE \`vehicle_public_images_public_image\` DROP FOREIGN KEY \`FK_e7ac12dd5b1b78be3b73e36a273\``);
        await queryRunner.query(`ALTER TABLE \`vehicle_public_images_public_image\` DROP FOREIGN KEY \`FK_4cf8fe8129ab729e46f3b656ca2\``);
        await queryRunner.query(`ALTER TABLE \`vehicle_pilots_person\` DROP FOREIGN KEY \`FK_c73dfb1a6855a3090a53f1775db\``);
        await queryRunner.query(`ALTER TABLE \`starship_file_images_file_image\` DROP FOREIGN KEY \`FK_1f9ba49219eba1e6bff2a6d0c8b\``);
        await queryRunner.query(`ALTER TABLE \`starship_file_images_file_image\` DROP FOREIGN KEY \`FK_70c9f6c4cbf97078fec8a3c3f4c\``);
        await queryRunner.query(`ALTER TABLE \`starship_public_images_public_image\` DROP FOREIGN KEY \`FK_9f5a82d306b4d5ccded99965a7c\``);
        await queryRunner.query(`ALTER TABLE \`starship_public_images_public_image\` DROP FOREIGN KEY \`FK_16dde91fda64eeb31e5baa1b651\``);
        await queryRunner.query(`ALTER TABLE \`starship_pilots_person\` DROP FOREIGN KEY \`FK_c288e78f5f06c73e7f7dc0d0987\``);
        await queryRunner.query(`ALTER TABLE \`planet_file_images_file_image\` DROP FOREIGN KEY \`FK_c3333884b9d04c6c185f8695e37\``);
        await queryRunner.query(`ALTER TABLE \`planet_file_images_file_image\` DROP FOREIGN KEY \`FK_4def93684640f79d8b410292d08\``);
        await queryRunner.query(`ALTER TABLE \`planet_public_images_public_image\` DROP FOREIGN KEY \`FK_02c5bb34fb700872404edb40a6f\``);
        await queryRunner.query(`ALTER TABLE \`planet_public_images_public_image\` DROP FOREIGN KEY \`FK_5e3ba9988de63b7c2428979f066\``);
        await queryRunner.query(`ALTER TABLE \`species_file_images_file_image\` DROP FOREIGN KEY \`FK_b5e76ce0c5ce1249d7fe8857f0e\``);
        await queryRunner.query(`ALTER TABLE \`species_file_images_file_image\` DROP FOREIGN KEY \`FK_a28aa9ef8ff2322342334e91f7e\``);
        await queryRunner.query(`ALTER TABLE \`species_public_images_public_image\` DROP FOREIGN KEY \`FK_8542c2cb80cd87ed017de247b4e\``);
        await queryRunner.query(`ALTER TABLE \`species_public_images_public_image\` DROP FOREIGN KEY \`FK_d99989c589c00013b81c3a3b3b0\``);
        await queryRunner.query(`ALTER TABLE \`person\` DROP FOREIGN KEY \`FK_e9797533c90a8211d39784488f3\``);
        await queryRunner.query(`ALTER TABLE \`species\` DROP FOREIGN KEY \`FK_f7e93a1974cc86fd87ce6777319\``);
        await queryRunner.query(`ALTER TABLE \`person\` CHANGE \`homeworld_id\` \`homeworld_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`person\` ADD CONSTRAINT \`FK_e9797533c90a8211d39784488f3\` FOREIGN KEY (\`homeworld_id\`) REFERENCES \`planet\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`species\` CHANGE \`homeworld_id\` \`homeworld_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`species\` ADD CONSTRAINT \`FK_f7e93a1974cc86fd87ce6777319\` FOREIGN KEY (\`homeworld_id\`) REFERENCES \`planet\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`planet\` DROP COLUMN \`diameter\``);
        await queryRunner.query(`DROP INDEX \`IDX_ad877fc7ae8d3269c736ec6c2e\` ON \`film_file_images_file_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_2b92c5667c380b56597819981e\` ON \`film_file_images_file_image\``);
        await queryRunner.query(`DROP TABLE \`film_file_images_file_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_b2b751a688065c8c8a1add7de2\` ON \`film_public_images_public_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_9aaf17ea2ecaf60637e871c14e\` ON \`film_public_images_public_image\``);
        await queryRunner.query(`DROP TABLE \`film_public_images_public_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_2f57c18a8452577561758c646d\` ON \`person_file_images_file_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_2c3ae1c800f91b77685ab2beda\` ON \`person_file_images_file_image\``);
        await queryRunner.query(`DROP TABLE \`person_file_images_file_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_18da4152da165885e90279fca2\` ON \`person_public_images_public_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_e6219cda4da6e388190be2389d\` ON \`person_public_images_public_image\``);
        await queryRunner.query(`DROP TABLE \`person_public_images_public_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_c0467899515f18bb82e5053e7a\` ON \`vehicle_file_images_file_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_2bcc119990ead7945ef8d0451c\` ON \`vehicle_file_images_file_image\``);
        await queryRunner.query(`DROP TABLE \`vehicle_file_images_file_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_e7ac12dd5b1b78be3b73e36a27\` ON \`vehicle_public_images_public_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_4cf8fe8129ab729e46f3b656ca\` ON \`vehicle_public_images_public_image\``);
        await queryRunner.query(`DROP TABLE \`vehicle_public_images_public_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_1f9ba49219eba1e6bff2a6d0c8\` ON \`starship_file_images_file_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_70c9f6c4cbf97078fec8a3c3f4\` ON \`starship_file_images_file_image\``);
        await queryRunner.query(`DROP TABLE \`starship_file_images_file_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_9f5a82d306b4d5ccded99965a7\` ON \`starship_public_images_public_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_16dde91fda64eeb31e5baa1b65\` ON \`starship_public_images_public_image\``);
        await queryRunner.query(`DROP TABLE \`starship_public_images_public_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_c3333884b9d04c6c185f8695e3\` ON \`planet_file_images_file_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_4def93684640f79d8b410292d0\` ON \`planet_file_images_file_image\``);
        await queryRunner.query(`DROP TABLE \`planet_file_images_file_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_02c5bb34fb700872404edb40a6\` ON \`planet_public_images_public_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_5e3ba9988de63b7c2428979f06\` ON \`planet_public_images_public_image\``);
        await queryRunner.query(`DROP TABLE \`planet_public_images_public_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_b5e76ce0c5ce1249d7fe8857f0\` ON \`species_file_images_file_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_a28aa9ef8ff2322342334e91f7\` ON \`species_file_images_file_image\``);
        await queryRunner.query(`DROP TABLE \`species_file_images_file_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_8542c2cb80cd87ed017de247b4\` ON \`species_public_images_public_image\``);
        await queryRunner.query(`DROP INDEX \`IDX_d99989c589c00013b81c3a3b3b\` ON \`species_public_images_public_image\``);
        await queryRunner.query(`DROP TABLE \`species_public_images_public_image\``);
        await queryRunner.query(`DROP TABLE \`public_image\``);
        await queryRunner.query(`DROP TABLE \`file_image\``);
        await queryRunner.query(`ALTER TABLE \`film_species_species\` ADD CONSTRAINT \`FK_f24ab6fc37cb0682cc6e9ecbea6\` FOREIGN KEY (\`species_id\`) REFERENCES \`species\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`film_vehicles_vehicle\` ADD CONSTRAINT \`FK_06a000ce716c9d51c5aab52d924\` FOREIGN KEY (\`vehicle_id\`) REFERENCES \`vehicle\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`film_starships_starship\` ADD CONSTRAINT \`FK_31c21f4a2e9b82e67edb2c0fce2\` FOREIGN KEY (\`starship_id\`) REFERENCES \`starship\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`film_planets_planet\` ADD CONSTRAINT \`FK_ab8496e34e9348472fa6297afad\` FOREIGN KEY (\`planet_id\`) REFERENCES \`planet\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`film_characters_person\` ADD CONSTRAINT \`FK_ac77e50e8297245fc2dec2208c5\` FOREIGN KEY (\`character_id\`) REFERENCES \`person\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`person_species_species\` ADD CONSTRAINT \`FK_57bacd286664d61d21d5bd226db\` FOREIGN KEY (\`species_id\`) REFERENCES \`species\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`vehicle_pilots_person\` ADD CONSTRAINT \`FK_c73dfb1a6855a3090a53f1775db\` FOREIGN KEY (\`pilot_id\`) REFERENCES \`person\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`starship_pilots_person\` ADD CONSTRAINT \`FK_c288e78f5f06c73e7f7dc0d0987\` FOREIGN KEY (\`pilot_id\`) REFERENCES \`person\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
